[package]
name = "compositor-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
# Phase 2: DRM device initialization
drm = "0.12"

[profile.release]
opt-level = "z"
lto = true
strip = true
panic = "abort"
